Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace WebAp.Models
{
    public class Car
    {
        
        public int Id { get; set; }

        [DisplayName("Марка")]
        public string Marka { get; set; }

        [DisplayName("Модель")]
        public string Model { get; set; }

        [DisplayName("Год выпуска")]
        public int GodVypuska { get; set; }
      
    }
}

Models/ErrorViewModel.cs
using System;

namespace WebAp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CarsController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using WebAp.Models;
using WebAp.Service;

namespace WebAp.Controllers
{
    public class CarsController : Controller
    {
        private readonly string ConnectionString = "User ID=postgres;Password=123;Host=localhost;Port=5432;Database=test123;";
        private IDbConnection con;
        private readonly ICarService _carService;

        public CarsController(ICarService carService)
        {
            _carService = carService;
        }

        public IActionResult Index()
        {
            var result = _carService.GetCar();
            return View("Index", result);
        }
        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Car auto)
        {
            _carService.Create(auto);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
           var car = _carService.Update(id);
           
            return View(car);
        }
        [HttpPost]
        public IActionResult Update(Car car)
        {
            _carService.Update(car);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public string Delete(int id)
        {
            return "OK";
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebAp.Models;

namespace WebAp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}
        public HomeController(IConfiguration config)
        {
            this._configuration = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cars/Create.cshtml
@model WebAp.Models.Car

@{
    ViewData["Title"] = "New Car";
}


<h4 >New Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GodVypuska" class="control-label"></label>
                <input asp-for="GodVypuska" class="form-control" />
                <span asp-validation-for="GodVypuska" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Back to List</a>
            </div>
        </form>
    </div>
</div>

Views/Cars/Index.cshtml
@model IEnumerable<WebAp.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Автомобили</h1>

<p>
    <a asp-action="Create" class="waves-effect waves-light btn">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <!-- <th>
                @Html.DisplayNameFor(model => model.Id)
            </th> -->
            <th>
                @Html.DisplayNameFor(model => model.Marka)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GodVypuska)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="car_@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Marka)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GodVypuska)
                </td>
                <td>
                    <a asp-controller="Cars" asp-action="Update" asp-route-id="@item.Id" class="waves-effect waves-light btn">Edit</a>
                </td>
                <td>
                    @*<form asp-controller="Cars" asp-action="Delete" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to delete the car @item.Marka?')">
                        <button type="submit" class="btn waves-effect waves-red btn-small red">Delete</button>
                    </form>*@
                    <a><button onclick="DeleteCar(@item.Id) " type="submit" class="btn waves-effect waves-red btn-small red">Delete</button></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    function DeleteCar(_id) {

        $.ajax({
            method: "POST",
            url: "/Cars/Delete",
            data: {
                id: _id
            },
            success: function (rsp) {
                console.log(rsp);
                if (rsp == "OK") {
                    alert("Удалено");
                }
                else {
                    alert("Ошибка");
                }
                document.getElementById('car_' + _id).style.display = "none";
            },
            error: function (e) {
                alert("Ошибка");
            }
        }
        )
    }

</script>

Views/Cars/Update.cshtml
@model WebAp.Models.Car

@{
    ViewData["Title"] = "Update the car " + Model.Marka;
}


<h4>Update the car @Model.Marka</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
                <input asp-for="Id" type="hidden" />
                
            <div class="form-group">
                <label asp-for="Marka" class="control-label"></label>
                <input asp-for="Marka" class="form-control" />
                <span asp-validation-for="Marka" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GodVypuska" class="control-label"></label>
                <input asp-for="GodVypuska" class="form-control" />
                <span asp-validation-for="GodVypuska" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-primary btn-sm" /> &emsp;
                <a asp-action="Index" class="btn btn-link btn-sm">Back to List</a>
            </div>
        </form>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/materialize.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebAp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <!-- <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>